# Framework coordinates
frameworkVersion=v1.0.2

# NexServiceRegistry version
registryVersion=v1.0.2

# Platform versions
paperVersion=1.21.11-R0.1-SNAPSHOT
velocityVersion=3.5.0-SNAPSHOT

# Tooling
lombokVersion=1.18.36

# Gradle tuning
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
kotlin.code.style=official